'------------------------------------------------------------------------------
' <auto-generated>
'    Este código se generó a partir de una plantilla.
'
'    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class categorias
    Public Property IdCategoria As Integer
    Public Property NombreCategoria As String
    Public Property Descripcion As String

    Public Overridable Property productos As ICollection(Of productos) = New HashSet(Of productos)

End Class
