'------------------------------------------------------------------------------
' <auto-generated>
'    Este código se generó a partir de una plantilla.
'
'    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class empleados
    Public Property IdEmpleado As Integer
    Public Property ApeEmpleado As String
    Public Property NomEmpleado As String
    Public Property FecNac As Date
    Public Property DirEmpleado As String
    Public Property idDistrito As Nullable(Of Integer)
    Public Property fonoEmpleado As String
    Public Property idCargo As Nullable(Of Integer)
    Public Property FecContrata As Date
    Public Property Activo As Nullable(Of Boolean)

    Public Overridable Property Cargos As Cargos
    Public Overridable Property Distritos As Distritos
    Public Overridable Property pedidoscabe As ICollection(Of pedidoscabe) = New HashSet(Of pedidoscabe)

End Class
