'------------------------------------------------------------------------------
' <auto-generated>
'    Este código se generó a partir de una plantilla.
'
'    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure
Imports System.Data.Objects
Imports System.Data.Objects.DataClasses
Imports System.Linq

Partial Public Class Negocios2015Entities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=Negocios2015Entities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Property categorias() As DbSet(Of categorias)
    Public Property productos() As DbSet(Of productos)
    Public Property proveedores() As DbSet(Of proveedores)
    Public Property Cargos() As DbSet(Of Cargos)
    Public Property Distritos() As DbSet(Of Distritos)
    Public Property empleados() As DbSet(Of empleados)
    Public Property clientes() As DbSet(Of clientes)
    Public Property paises() As DbSet(Of paises)
    Public Property pedidoscabe() As DbSet(Of pedidoscabe)
    Public Property pedidosdeta() As DbSet(Of pedidosdeta)

    Public Overridable Function usp_ClienteListar() As ObjectResult(Of usp_ClienteListar_Result)
        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of usp_ClienteListar_Result)("usp_ClienteListar")
    End Function

    Public Overridable Function usp_PedidoFechas(fec1 As Nullable(Of Date), fec2 As Nullable(Of Date)) As ObjectResult(Of usp_PedidoFechas_Result)
        Dim fec1Parameter As ObjectParameter = If(fec1.HasValue, New ObjectParameter("fec1", fec1), New ObjectParameter("fec1", GetType(Date)))

        Dim fec2Parameter As ObjectParameter = If(fec2.HasValue, New ObjectParameter("fec2", fec2), New ObjectParameter("fec2", GetType(Date)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of usp_PedidoFechas_Result)("usp_PedidoFechas", fec1Parameter, fec2Parameter)
    End Function

    Public Overridable Function f_Clientes_Listar() As ObjectResult(Of f_Clientes_Listar_Result)
        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of f_Clientes_Listar_Result)("f_Clientes_Listar")
    End Function

    Public Overridable Function usp_PedidosCliente(idCliente As String) As ObjectResult(Of usp_PedidosCliente_Result)
        Dim idClienteParameter As ObjectParameter = If(idCliente IsNot Nothing, New ObjectParameter("IdCliente", idCliente), New ObjectParameter("IdCliente", GetType(String)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of usp_PedidosCliente_Result)("usp_PedidosCliente", idClienteParameter)
    End Function

    Public Overridable Function usp_EmpleadoListar() As ObjectResult(Of usp_EmpleadoListar_Result)
        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of usp_EmpleadoListar_Result)("usp_EmpleadoListar")
    End Function

    Public Overridable Function usp_CargoListar() As ObjectResult(Of usp_CargoListar_Result)
        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of usp_CargoListar_Result)("usp_CargoListar")
    End Function

    Public Overridable Function usp_DistritoListar() As ObjectResult(Of usp_DistritoListar_Result)
        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of usp_DistritoListar_Result)("usp_DistritoListar")
    End Function

End Class
