'------------------------------------------------------------------------------
' <auto-generated>
'    Este código se generó a partir de una plantilla.
'
'    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class pedidoscabe
    Public Property IdPedido As Integer
    Public Property IdCliente As String
    Public Property IdEmpleado As Nullable(Of Integer)
    Public Property FechaPedido As Date
    Public Property FechaEntrega As Nullable(Of Date)
    Public Property FechaEnvio As Nullable(Of Date)
    Public Property EnvioPedido As String
    Public Property CantidaPedido As Nullable(Of Integer)
    Public Property Destinatario As String
    Public Property DirDestinatario As String
    Public Property CiuDestinatario As String
    Public Property RefDestnatario As String
    Public Property DepDestinatario As String
    Public Property PaiDestinatario As String

    Public Overridable Property empleados As empleados
    Public Overridable Property clientes As clientes
    Public Overridable Property pedidosdeta As ICollection(Of pedidosdeta) = New HashSet(Of pedidosdeta)

End Class
