'------------------------------------------------------------------------------
' <auto-generated>
'    Este código se generó a partir de una plantilla.
'
'    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class pedidosdeta
    Public Property IdPedido As Nullable(Of Integer)
    Public Property IdProducto As Nullable(Of Integer)
    Public Property PrecioUnidad As Decimal
    Public Property Cantidad As Short
    Public Property Descuento As Double

    Public Overridable Property productos As productos
    Public Overridable Property pedidoscabe As pedidoscabe

End Class
