'------------------------------------------------------------------------------
' <auto-generated>
'    Este código se generó a partir de una plantilla.
'
'    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class proveedores
    Public Property IdProveedor As Integer
    Public Property NomProveedor As String
    Public Property DirProveedor As String
    Public Property NomContacto As String
    Public Property CargoContacto As String
    Public Property idpais As String
    Public Property fonoProveedor As String
    Public Property FaxProveedor As String

    Public Overridable Property productos As ICollection(Of productos) = New HashSet(Of productos)
    Public Overridable Property paises As paises

End Class
